export const vinStyle = {
  mainwrapper: 'grid sm:grid-cols-2 md:grid-cols-2 gap-8 mx-10 my-5 font-toyota',
  innerWrapper: 'grid sm:grid-cols-2 md:grid-cols-2 gap-5 p-5 bg-white',
  innerWrapperError: 'flex p-5 bg-white items-center justify-center font-bold',
  displayFlex: 'flex',
  prevVehicle:'mr-5 font-medium md:mr-1 lg:mr-5',
  nextVehicle:'mr-5 font-medium md:mr-1 lg:mr-16',
  currentVehicle:'mr-5 font-medium md:mr-1 lg:mr-1',
  complete_prev: 'bg-grey font-semibold px-2 md:pt-3 lg:py-1 rounded-md border-2 border-black text-sm',
  complete_on_time: "bg-green1 font-semibold px-2 md:pt-3 lg:py-1 rounded-md text-sm text-white",
  complete_late: "bg-red1 font-semibold px-2 md:pt-3 lg:py-1 rounded-md text-sm text-white",
  ongoing: "bg-blue1 font-semibold px-2 md:pt-3 lg:py-1 rounded-md text-sm text-white",
  complete: "bg-grey2 font-semibold px-2 md:pt-3 lg:py-1 rounded-md text-sm",
  incomplete: "bg-grey2 font-semibold px-2 md:pt-3 lg:py-1 rounded-md text-sm",
  marginTop: 'mt-5',
  semiBold:'font-semibold',
  fontSize: 'font-medium text-sm',
  marginFontSize:'mr-5 text-sm',
  labelStaging:'bg-white font-semibold px-2 py-1 rounded-md border-2 border-black text-sm',
  labelPending:'bg-orange1 text-white font-semibold px-2 py-1 rounded-md text-sm',
  plannedTime:'flex items-center justify-between font-medium text-sm',
  vehicleBorderBlue:'border-2 border-blue1 rounded',
  vehicleBorderRed:'border-2 border-red1 rounded bg-red3',
  vehicleCompleteLate:'bg-red1 bg-red3',
  vehicleImageNotFound: 'font-bold p-32'
};
