export const productionLineMetricStyle = {
    productionLineMainWrapper: 'w-full grid grid-cols-12',
    productionLineSubWrapper: 'col-span-8 mt-5 mb-10 ml-10',
    productionLineMetricsWrapper: 'w-full grid grid-cols-12',
    productionLineDropdownWrapper: 'col-span-3 mb-10 ml-10',
    productionLineShopName: 'text-xs text-grey4 mb-3',
    productionLineDropdownHeader: 'mb-4',
    productionLineDropdown: 'block w-48 px-4 py-2 text-gray-700 bg-white border rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500',
    productionLineMetricWrapper: 'col-span-9 mb-10 ml-10',
    productionLineMetricSubWrapper: 'bg-white mr-8 px-4 py-8',
    productionLineMetricsFont: 'font-semibold text-base',
    productionLineChartWrapper: 'mt-10 mr-8',
    productionLineProgressSummaryWrapper: 'mt-10 mr-8',
    productionLineProgressSummaryHeader: 'text-white bg-black p-4 text-xs font-bold font-toyota',
    productionLineStallStatus: 'col-span-4 bg-white px-4 py-4 mt-5 mb-10 mr-10',
    productionLineStallStatusHeader: 'font-semibold text-base',
    productionLineProgressSummaryOuterWrapper: 'w-full grid md:grid-cols-1 lg:grid-cols-1',
    productionLineProgressExceptionSummaryOuterWrapper: 'w-full grid md:grid-cols-1 lg:grid-cols-5',
    cardHover: 'absolute -top-[3px] left-[35px] w-[100px] rotate-180 z-1000 flex flex-col invisible mb-6 group-hover:visible',
    spanHover: 'z-1000 rotate-180 rounded p-2 text-xs leading-none text-left text-white whitespace-no-wrap bg-black shadow-lg',
    tooltipHover:'flex justify-between',
    tooltipMargin:'mr-10',
    divider:  'relative left-[95px] -bottom-[20px] w-3 h-3 -mt-2 rotate-45 bg-black',
    cardHoverHours: 'absolute -top-[17px] left-[10vw] w-[150px] rotate-180 z-1000 flex flex-col invisible mb-6 group-hover:visible',
    dividerHours:  'relative left-[143px] -bottom-[65px] w-3 h-3 -mt-2 rotate-45 bg-black',
    cardHoverStallUtilization: 'absolute -top-6 left-[12vw] w-[250px] rotate-180 z-1000 flex flex-col invisible mb-6 group-hover/thtooltip:visible',
    dividerStallUtilization:  'relative left-[243px] -bottom-[20px] w-3 h-3 -mt-2 rotate-45 bg-black',
    cardHoverCurrentStallPerformance: 'absolute -top-7 left-[13vw] w-[550px] rotate-180 z-2000 flex flex-col invisible mb-6 group-hover/thtooltip:visible',
    cardHoverStallPerformance: 'absolute -top-7 left-[11vw] w-[400px] rotate-180 z-2000 flex flex-col invisible mb-6 group-hover/thtooltip:visible',
    dividerCurrentStallPerformance:  'relative left-[543px] -bottom-[27px] w-3 h-3 -mt-2 rotate-45 bg-black',
    dividerStallPerformance:  'relative left-[392px] -bottom-[27px] w-3 h-3 -mt-2 rotate-45 bg-black',
    cardHoverProgress: 'absolute -top-7 left-[7vw] w-[475px] rotate-180 z-2000 flex flex-col invisible mb-6 group-hover/thtooltip:visible',
    dividerProgress:  'relative left-[468px] -bottom-[28px] w-3 h-3 -mt-2 rotate-45 bg-black',
    cardHoverStatus: 'absolute -top-7 left-[6vw] w-[475px] rotate-180 z-2000 flex flex-col invisible mb-6 group-hover/thtooltip:visible',
    dividerStatus:  'relative left-[468px] -bottom-[28px] w-3 h-3 -mt-2 rotate-45 bg-black',
    cardHoverCurrentStatus: 'relative -top-7 left-[7vw] pl-5em w-[475px] rotate-180 z-2000 flex flex-col absolute ml-2 invisible mb-6 group-hover/thtooltip:visible',
    dividerCurrentStatus:  'relative left-[468px] -bottom-[25px] w-3 h-3 -mt-2 rotate-45 bg-black' 
}