export const vinStyle = {
    buttonColorBlack: 'bg-black',
    buttonColorBlue: 'bg-blue-600 hover:bg-blue-700rounded',
    buttonColorDisabled: 'bg-grey',
    buttonColorInstalled:'bg-grey5',
    buttonColorAccessoryInstalled:'bg-green1',
    buttonColorNotInstalled:'bg-red1',
    button: 'flex focus:outline-none text-white text-sm sm:text-base py-2 px-4 rounded',
    btnMargin: 'mr-5',
    buttonWidth: 'flex w-full items-end justify-end py-5 font-toyota bg-white',
    statusPadding:'p-4',
    statusListWrapper:'text-sm border-b border-grey2 mb-2',
    statusFont:'font-semibold',
    notInstalled:'focus:outline-none text-white text-xl mb-2 rounded p-2',
    accessoryInstalled:'text-white text-xl mb-2 rounded p-2',
    accessoryLabel:'px-3.5 py-4 text-grey4 font-normal',
    accessoryStatusLabel: 'px-3.5 py-4 text-grey4 font-normal text-right',
    tooltipOuterWrapper: 'px-3.5 py-4 text-grey4',
    tooltipInnerWrapper: 'group relative w-max',
    tooltipLabel: 'font-normal',
    tooltipButton: 'bg-blue1 text-white active:bg-blue1 font-bold  ml-3 px-2 py-px rounded-full shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150',
    tooltipSpan: 'absolute -bottom-72 left-1 w-max rounded text-black bg-white py-4 pl-4 pr-14 invisible shadow transition-opacity group-hover:visible font-normal',
    accessoryTableBody:'group',
    accessoryTableMainWrapper: 'flex flex-col',
    accessoryTableInnerWrapper: 'overflow-x-auto',
    accessoryTableWidth: 'inline-block min-w-full',
    accessoryTableOverflow: 'overflow-hidden',
    accessoryTableScroll: 'h-60v overflow-y-scroll',
    accessoryTableFont: 'min-w-full text-left text-sm font-toyota',
    accessoryTableBackground: 'bg-white text-sm',
    accessoryListWrap: 'whitespace-nowrap px-3.5 py-4',
    accessoryListWrapLink: 'whitespace-nowrap px-3.5 py-4 text-blue1',
    accessoryListWrapOpacity: 'whitespace-nowrap px-3.5 py-4 opacity-100',
    accessoryReasonLabel:'whitespace-nowrap py-4',
    accessoryReasonHeight:'h-10',
    accessoryTableListGrey:'bg-grey3',
    accessoryTableListWhite:'bg-white',
}