export const shopFloorLBStyle = {
    mainWrapper: 'w-full',
    container: 'px-4 py-8 text-center',
    buildingWrapper: 'grid grid-cols-12 gap-4',
    leftBuilding: 'col-span-7 flex justify-between overflow-x-scroll border border-grey px-3.5 py-4 flex-wrap',
    leftBuildingHeaderText: 'font-semibold font-toyota sticky left-0 w-full text-left ml-3.5 text-base',
    leftBuildingHeaderTextMiddle: 'font-semibold font-toyota sticky left-0 w-full text-left ml-3 text-base truncate',
    shopFloorBodyWrapper: 'flex gap-4 justify-between border-grey px-2.5 py-4 h-48',
    middleBuilding: 'col-span-1 flex justify-between overflow-x-scroll border border-grey px-0 py-4 flex-wrap',
    rightBuilding: 'col-span-4 flex justify-between overflow-x-scroll border border-grey px-2.5 py-4 flex-wrap',
    whitespace: 'grid grid-cols-12 gap-8 h-16',
    innerWhitespace1: 'col-span-5',
    innerWhitespace2: 'col-span-1',
    innerWhitespace3: 'col-span-2',
    innerWhitespace4: 'col-span-1',
    innerWhitespace5: 'col-span-2',
    FPR_FUEL_PPOP_CONTAINER: 'grid grid-cols-12',
    FPR: 'col-span-1 flex justify-center items-center border border-grey rounded p-2 bg-grey6',
    FPR_LINE: 'col-span-1 grid grid-flow-row divide-y-2 > * + * divide-grey2',
    FUEL_WASH: 'col-span-1 flex flex-col justify-center items-center border border-grey rounded p-2 bg-grey6',
    FUEL_WASH_DIVIDER: 'col-span-1 grid grid-flow-row divide-y-2 > * + * divide-grey2',
    PPO_SHOP_STAGING: 'col-span-2 flex flex-col justify-center items-center border border-grey rounded p-2 bg-grey6',
    PPO_STAGING_DIVIDER: 'col-span-1 grid grid-flow-row divide-y-2 > * + * divide-grey2',
    CONVEYOR_STAGING: 'col-span-1 flex flex-col justify-center items-center border border-grey rounded p-2 bg-grey6',
    CONVEYOR_STAGING_DIVIDER: 'col-span-1 grid grid-flow-row divide-y-2 > * + * divide-grey2',
    FQA_STAGING: 'col-span-1 flex flex-col justify-center items-center border border-grey rounded p-2 bg-grey6',
    FQA_STAGING_DIVIDER: 'col-span-1 grid grid-flow-row divide-y-2 > * + * divide-grey2',
    LPR: 'col-span-1 flex flex-col justify-center items-center border border-grey rounded p-2 bg-grey6',
    FPR_LPR_CONTAINER: 'grid grid-cols-12',
    FPR_LPR_FIRST_BOX: 'col-span-1 border border-grey rounded p-2 bg-grey6',
    FPR_LPR_SECOND_BOX: 'col-span-1 border border-grey rounded p-2 bg-grey6',
    FPR_LPR_DIVIDER: 'col-span-10 grid grid-flow-row divide-y-2 > * + * divide-grey2',
}
